namespace Mytime.Distribution.Utils.Helpers
{
    /// <summary>
    /// 快递编码
    /// </summary>
    public class KuaidiCode
    {
        /// <summary>
        /// 标题
        /// </summary>
        /// <value></value>
        public string Title { get; set; }
        /// <summary>
        /// 编码
        /// </summary>
        /// <value></value>
        public string Code { get; set; }
    }

    /// <summary>
    /// 快递100编码
    /// </summary>
    public class Kuaidi100Code
    {
        /// <summary>
        /// 编码
        /// </summary>
        /// <value></value>
        public static string Codes = @"[{'title':'圆通速递','code':'yuantong'},
{'title':'韵达快递','code':'yunda'},
{'title':'中通快递','code':'zhongtong'},
{'title':'邮政快递包裹','code':'youzhengguonei'},
{'title':'百世快递','code':'huitongkuaidi'},
{'title':'顺丰速运','code':'shunfeng'},
{'title':'申通快递','code':'shentong'},
{'title':'京东物流','code':'jd'},
{'title':'EMS','code':'ems'},
{'title':'天天快递','code':'tiantian'},
{'title':'极兔速递','code':'jtexpress'},
{'title':'邮政标准快递','code':'youzhengbk'},
{'title':'德邦','code':'debangwuliu'},
{'title':'德邦快递','code':'debangkuaidi'},
{'title':'众邮快递','code':'zhongyouex'},
{'title':'宅急送','code':'zhaijisong'},
{'title':'优速快递','code':'youshuwuliu'},
{'title':'百世快运','code':'baishiwuliu'},
{'title':'苏宁物流','code':'suning'},
{'title':'wedepot物流','code':'wedepot'},
{'title':'圆通快运','code':'yuantongkuaiyun'},
{'title':'韵达快运','code':'yundakuaiyun'},
{'title':'中通快运','code':'zhongtongkuaiyun'},
{'title':'安能快运','code':'annengwuliu'},
{'title':'特急送','code':'lntjs'},
{'title':'DHL-全球件','code':'dhlen'},
{'title':'速必达','code':'subida'},
{'title':'UPS-全球件','code':'upsen'},
{'title':'FedEx-国际件','code':'fedex'},
{'title':'中通国际','code':'zhongtongguoji'},
{'title':'跨越速运','code':'kuayue'},
{'title':'USPS','code':'usps'},
{'title':'D速快递','code':'dsukuaidi'},
{'title':'DHL-中国件','code':'dhl'},
{'title':'丹鸟','code':'danniao'},
{'title':'壹米滴答','code':'yimidida'},
{'title':'国际包裹','code':'youzhengguoji'},
{'title':'安得物流','code':'annto'},
{'title':'EMS-国际件','code':'emsguoji'},
{'title':'速尔快递','code':'suer'},
{'title':'UPS','code':'ups'},
{'title':'日日顺物流','code':'rrs'},
{'title':'芝麻开门','code':'zhimakaimen'},
{'title':'微特派','code':'weitepai'},
{'title':'YUN TRACK','code':'yuntrack'},
{'title':'EWE全球快递','code':'ewe'},
{'title':'招金精炼','code':'zhaojin'},
{'title':'同城快寄','code':'shpost'},
{'title':'顺心捷达','code':'sxjdfreight'},
{'title':'联昊通','code':'lianhaowuliu'},
{'title':'递四方','code':'disifang'},
{'title':'京广速递','code':'jinguangsudikuaijian'},
{'title':'大马鹿','code':'idamalu'},
{'title':'快捷速递','code':'kuaijiesudi'},
{'title':'信丰物流','code':'xinfengwuliu'},
{'title':'联合快递','code':'gslhkd'},
{'title':'国通快递','code':'guotongkuaidi'},
{'title':'Fedex-国际件-中文','code':'fedexcn'},
{'title':'顺丰快运','code':'shunfengkuaiyun'},
{'title':'宇鑫物流','code':'yuxinwuliu'},
{'title':'卓志速运','code':'chinaicip'},
{'title':'优邦速运','code':'ubonex'},
{'title':'美快国际物流','code':'meiquick'},
{'title':'新顺丰（NSF）','code':'nsf'},
{'title':'TNT','code':'tnt'},
{'title':'广东邮政','code':'guangdongyouzhengwuliu'},
{'title':'加运美','code':'jiayunmeiwuliu'},
{'title':'全峰快递','code':'quanfengkuaidi'},
{'title':'九曳供应链','code':'jiuyescm'},
{'title':'澳洲飞跃物流','code':'rlgaus'},
{'title':'如风达','code':'rufengda'},
{'title':'日本（Japan Post）','code':'japanposten'},
{'title':'中邮物流','code':'zhongyouwuliu'},
{'title':'中邮速递','code':'wondersyd'},
{'title':'京东快运','code':'jingdongkuaiyun'},
{'title':'CJ物流','code':'doortodoor'},
{'title':'广东速腾物流','code':'suteng'},
{'title':'申通国际','code':'stosolution'},
{'title':'澳邮中国快运','code':'auexpress'},
{'title':'威盛快递','code':'wherexpess'},
{'title':'联邦快递','code':'lianbangkuaidi'},
{'title':'鑫正一快递','code':'zhengyikuaidi'},
{'title':'转运中国','code':'uszcn'},
{'title':'圆通国际','code':'yuantongguoji'},
{'title':'天马迅达','code':'tianma'},
{'title':'Austa国际速递','code':'austa'},
{'title':'邦泰快运','code':'btexpress'},
{'title':'龙邦速递','code':'longbanwuliu'},
{'title':'增益速递','code':'zengyisudi'},
{'title':'Xlobo贝海国际','code':'xlobo'},
{'title':'泛捷国际速递','code':'epanex'},
{'title':'金岸物流','code':'jinan'},
{'title':'疯狂快递','code':'crazyexpress'},
{'title':'德国优拜物流','code':'ubuy'},
{'title':'燕文物流','code':'yw56'},
{'title':'汇森速运','code':'huisenky'},
{'title':'平安达腾飞','code':'pingandatengfei'},
{'title':'速达通','code':'sdto'},
{'title':'中远e环球','code':'cosco'},
{'title':'程光快递','code':'flyway'},
{'title':'海信物流','code':'savor'},
{'title':'TNT-全球件','code':'tnten'},
{'title':'EMS包裹','code':'emsbg'},
{'title':'天地华宇','code':'tiandihuayu'},
{'title':'御风速运','code':'yufeng'},
{'title':'Superb Grace','code':'superb'},
{'title':'安能快递','code':'ane66'},
{'title':'龙邦物流','code':'lbex'},
{'title':'中铁快运','code':'ztky'},
{'title':'DPD','code':'dpd'},
{'title':'EMS-国际件-英文','code':'emsinten'},
{'title':'运通速运','code':'yuntong'},
{'title':'OCS','code':'ocs'},
{'title':'转运四方','code':'zhuanyunsifang'},
{'title':'法国小包（colissimo）','code':'colissimo'},
{'title':'长江国际速递','code':'changjiang'},
{'title':'中铁飞豹','code':'zhongtiewuliu'},
{'title':'盛丰物流','code':'sfwl'},
{'title':'顺达快递','code':'sundarexpress'},
{'title':'新杰物流','code':'sunjex'},
{'title':'富腾达国际货运','code':'ftd'},
{'title':'盛辉物流','code':'shenghuiwuliu'},
{'title':'富吉速运','code':'fujisuyun'},
{'title':'方舟速递','code':'arkexpress'},
{'title':'优优速递','code':'youyou'},
{'title':'叁虎物流','code':'sanhuwuliu'},
{'title':'鼎润物流','code':'la911'},
{'title':'皮牙子快递','code':'bazirim'},
{'title':'中国香港(HongKong Post)','code':'hkpost'},
{'title':'斑马物流','code':'banma'},
{'title':'出口易','code':'chukou1'},
{'title':'无忧物流','code':'aliexpress'},
{'title':'源安达','code':'yuananda'},
{'title':'速通物流','code':'sut56'},
{'title':'澳大利亚(Australia Post)','code':'auspost'},
{'title':'黄马甲','code':'huangmajia'},
{'title':'汇通天下物流','code':'httx56'},
{'title':'比利时（Bpost）','code':'bpost'},
{'title':'Aramex','code':'aramex'},
{'title':'DHL-德国件（DHL Deutschland）','code':'dhlde'},
{'title':'易客满','code':'ecmscn'},
{'title':'德坤物流','code':'dekuncn'},
{'title':'安迅物流','code':'anxl'},
{'title':'联邦快递-英文','code':'lianbangkuaidien'},
{'title':'万象物流','code':'wanxiangwuliu'},
{'title':'集先锋快递','code':'jxfex'},
{'title':'联合速运','code':'unitedex'},
{'title':'极地快递','code':'polarexpress'},
{'title':'TST速运通','code':'tstexp'},
{'title':'佳怡物流','code':'jiayiwuliu'},
{'title':'达发物流','code':'dfwl'},
{'title':'时达通','code':'jssdt56'},
{'title':'新元国际','code':'xynyc'},
{'title':'AAE-中国件','code':'aae'},
{'title':'中环快递','code':'zhonghuan'},
{'title':'快捷快物流','code':'gdkjk56'},
{'title':'顺捷美中速递','code':'passerbyaexpress'},
{'title':'全速物流','code':'quansu'},
{'title':'宅急便','code':'zhaijibian'},
{'title':'速派快递','code':'fastgoexpress'},
{'title':'一速递','code':'oneexpress'},
{'title':'大田物流','code':'datianwuliu'},
{'title':'Highsince','code':'highsince'},
{'title':'百福东方','code':'baifudongfang'},
{'title':'万家物流','code':'wanjiawuliu'},
{'title':'鸿泰物流','code':'hnht56'},
{'title':'易达通快递','code':'qexpress'},
{'title':'GLS','code':'gls'},
{'title':'嘉里大通','code':'jialidatong'},
{'title':'EMS-英文','code':'emsen'},
{'title':'TNT Australia','code':'tntau'},
{'title':'环球速运','code':'huanqiu'},
{'title':'三态速递','code':'santaisudi'},
{'title':'华美快递','code':'hmus'},
{'title':'南方传媒物流','code':'ndwl'},
{'title':'成都立即送','code':'lijisong'},
{'title':'7号速递','code':'express7th'},
{'title':'安达速递','code':'adapost'},
{'title':'中速快递','code':'zhongsukuaidi'},
{'title':'苏通快运','code':'zjstky'},
{'title':'加拿大(Canada Post)','code':'canpost'},
{'title':'美通','code':'valueway'},
{'title':'COE','code':'coe'},
{'title':'全联速运','code':'guexp'},
{'title':'新西兰（New Zealand Post）','code':'newzealand'},
{'title':'邮邦国际','code':'youban'},
{'title':'上海缤纷物流','code':'bflg'},
{'title':'JDIEX','code':'jdiex'},
{'title':'澳天速运','code':'aotsd'},
{'title':'考拉速递','code':'koalaexp'},
{'title':'恒路物流','code':'hengluwuliu'},
{'title':'CNE','code':'cnexps'},
{'title':'聚盟共建','code':'jumstc'},
{'title':'景光物流','code':'jgwl'},
{'title':'合众速递(UCS）','code':'ucs'},
{'title':'CDEK','code':'cdek'},
{'title':'速递中国','code':'sendtochina'},
{'title':'迅达速递','code':'xdexpress'},
{'title':'德国(Deutsche Post)','code':'deutschepost'},
{'title':'UBI Australia','code':'gotoubi'},
{'title':'美国申通','code':'stoexpress'},
{'title':'佐川急便','code':'sagawa'},
{'title':'海带宝','code':'haidaibao'},
{'title':'乌克兰邮政包裹','code':'ukrpostcn'},
{'title':'宏递快运','code':'hd'},
{'title':'铁中快运','code':'tzky'},
{'title':'易境达国际物流','code':'uscbexpress'},
{'title':'一智通','code':'1ziton'},
{'title':'DHL Benelux','code':'dhlbenelux'},
{'title':'百腾物流','code':'baitengwuliu'},
{'title':'耀飞同城快递','code':'yaofeikuaidi'},
{'title':'西班牙(Correos de Espa?a)','code':'correosdees'},
{'title':'丰通快运','code':'ftky365'},
{'title':'英国大包、EMS（Parcel Force）','code':'parcelforce'},
{'title':'顺丰-繁体','code':'shunfenghk'},
{'title':'韩国邮政','code':'koreapostcn'},
{'title':'万家通快递','code':'timedg'},
{'title':'佳吉快运','code':'jiajiwuliu'},
{'title':'澳德物流','code':'auod'},
{'title':'SYNSHIP快递','code':'synship'},
{'title':'安信达','code':'anxindakuaixi'},
{'title':'商桥物流','code':'shangqiao56'},
{'title':'CNPEX中邮快递','code':'cnpex'},
{'title':'百事亨通','code':'bsht'},
{'title':'中翼国际物流','code':'chnexp'},
{'title':'安鲜达','code':'exfresh'},
{'title':'三真驿道','code':'zlink'},
{'title':'泛远国际物流','code':'farlogistis'},
{'title':'LUCFLOW EXPRESS','code':'longfx'},
{'title':'EFS Post（平安快递）','code':'efs'},
{'title':'顺丰同城','code':'shunfengtongcheng'},
{'title':'原飞航','code':'yuanfeihangwuliu'},
{'title':'广东诚通物流','code':'gdct56'},
{'title':'飞洋快递','code':'shipgce'},
{'title':'运通中港','code':'yuntongkuaidi'},
{'title':'店通快递','code':'diantongkuaidi'},
{'title':'瀚朝物流','code':'hac56'},
{'title':'FedEx-美国件','code':'fedexus'},
{'title':'荷兰邮政-中文(PostNL international registered mail)','code':'postnlcn'},
{'title':'运通中港快递','code':'ytkd'},
{'title':'小飞侠速递','code':'cyxfx'},
{'title':'DPEX','code':'dpex'},
{'title':'洋包裹','code':'yangbaoguo'},
{'title':'中集冷云','code':'cccc58'},
{'title':'全时速运','code':'runhengfeng'},
{'title':'老司机国际快递','code':'driverfastgo'},
{'title':'签收快递','code':'signedexpress'},
{'title':'锋鸟物流','code':'beebird'},
{'title':'顺捷达','code':'shunjieda'},
{'title':'广东通路','code':'guangdongtonglu'},
{'title':'星云速递','code':'nebuex'},
{'title':'Canpar','code':'canpar'},
{'title':'UEQ快递','code':'ueq'},
{'title':'明通国际快递','code':'tnjex'},
{'title':'佰麒快递','code':'beckygo'},
{'title':'商壹国际物流','code':'com1express'},
{'title':'全一快递','code':'quanyikuaidi'},
{'title':'法国(La Poste)','code':'csuivi'},
{'title':'E速达','code':'exsuda'},
{'title':'意大利(Poste Italiane)','code':'italiane'},
{'title':'Asendia USA','code':'asendiausa'},
{'title':'城晓国际快递','code':'ckeex'},
{'title':'上海航瑞货运','code':'hangrui'},
{'title':'急先达','code':'jixianda'},
{'title':'龙枫国际快递','code':'lfexpress'},
{'title':'久久物流','code':'jiujiuwl'},
{'title':'八达通','code':'bdatong'},
{'title':'Gati-中文','code':'gaticn'},
{'title':'Hermes','code':'hermes'},
{'title':'荷兰邮政-中国件','code':'postnlchina'},
{'title':'晟邦物流','code':'nanjingshengbang'},
{'title':'airpak expresss','code':'airpak'},
{'title':'优速通达','code':'yousutongda'},
{'title':'荷兰邮政(PostNL international registered mail)','code':'postnl'},
{'title':'直德邮','code':'zdepost'},
{'title':'dhl小包','code':'dhlecommerce'},
{'title':'好来运','code':'hlyex'},
{'title':'安捷物流','code':'anjie88'},
{'title':'CHS中环国际快递','code':'chszhonghuanguoji'},
{'title':'全速通','code':'quansutong'},
{'title':'Newgistics','code':'newgistics'},
{'title':'尚橙物流','code':'shangcheng'},
{'title':'宇佳物流','code':'yujiawl'},
{'title':'锦程快递','code':'hrex'},
{'title':'飞远配送','code':'feiyuanvipshop'},
{'title':'韩国（Korea Post）','code':'koreapost'},
{'title':'品骏快递','code':'pjbest'},
{'title':'一正达速运','code':'yizhengdasuyun'},
{'title':'一号线','code':'lineone'},
{'title':'黑猫宅急便','code':'tcat'},
{'title':'西游寄','code':'xiyoug'},
{'title':'上大物流','code':'shangda'},
{'title':'台湾（中华邮政）','code':'postserv'},
{'title':'智通物流','code':'ztong'},
{'title':'瑞典（Sweden Post）','code':'ruidianyouzheng'},
{'title':'能达速递','code':'ganzhongnengda'},
{'title':'家家通快递','code':'newsway'},
{'title':'迅速快递','code':'xunsuexpress'},
{'title':'中国香港(HongKong Post)英文','code':'hkposten'},
{'title':'骏丰国际速递','code':'junfengguoji'},
{'title':'丰程物流','code':'sccod'},
{'title':'LaserShip','code':'lasership'},
{'title':'OnTrac','code':'ontrac'},
{'title':'中邮电商','code':'chinapostcb'},
{'title':'东方汇','code':'est365'},
{'title':'海派国际速递','code':'hpexpress'},
{'title':'金大物流','code':'jindawuliu'},
{'title':'春风物流','code':'spring56'},
{'title':'卡塔尔（Qatar Post）','code':'qpost'},
{'title':'雪域易购','code':'qhxyyg'},
{'title':'城通物流','code':'chengtong'},
{'title':'飞豹快递','code':'feibaokuaidi'},
{'title':'圣安物流','code':'shenganwuliu'},
{'title':'亚洲顺物流','code':'yzswuliu'},
{'title':'EMS物流','code':'emswuliu'},
{'title':'荷兰包裹(PostNL International Parcels)','code':'postnlpacle'},
{'title':'Toll','code':'dpexen'},
{'title':'递五方云仓','code':'di5pll'},
{'title':'泰国138国际物流','code':'sd138'},
{'title':'合心速递','code':'hexinexpress'},
{'title':'TransRush','code':'transrush'},
{'title':'永昌物流','code':'yongchangwuliu'},
{'title':'魔速达','code':'mosuda'},
{'title':'一起送','code':'yiqisong'},
{'title':'传喜物流','code':'chuanxiwuliu'},
{'title':'淘布斯国际物流','code':'taoplus'},
{'title':'易达通','code':'yidatong'},
{'title':'佳吉快递','code':'jiajikuaidi'},
{'title':'三象速递','code':'sxexpress'},
{'title':'佳成快递 ','code':'jiacheng'},
{'title':'星空国际','code':'wlwex'},
{'title':'51跨境通','code':'wykjt'},
{'title':'欧亚专线','code':'euasia'},
{'title':'明达国际速递','code':'tmwexpress'},
{'title':'承诺达','code':'ytchengnuoda'},
{'title':'展勤快递','code':'byht'},
{'title':'飞康达','code':'feikangda'},
{'title':'秦远物流','code':'qinyuan'},
{'title':'天翼快递','code':'tykd'},
{'title':'比利时国际(Bpost international)','code':'bpostinter'},
{'title':'喀麦隆(CAMPOST)','code':'cameroon'},
{'title':'诚和通','code':'cht361'},
{'title':'速舟物流','code':'cnspeedster'},
{'title':'日本郵便','code':'japanpost'},
{'title':'景顺物流','code':'jingshun'},
{'title':'GTS快递','code':'gts'},
{'title':'安世通快递','code':'astexpress'},
{'title':'德尚国际速递','code':'gslexpress'},
{'title':'大洋物流','code':'dayangwuliu'},
{'title':'飞力士物流','code':'flysman'},
{'title':'宇航通物流','code':'yhtlogistics'},
{'title':'GSM','code':'gsm'},
{'title':'俄顺达','code':'eshunda'},
{'title':'捷安达','code':'jieanda'},
{'title':'鹏远国际速递','code':'pengyuanexpress'},
{'title':'CCES/国通快递','code':'cces'},
{'title':'track-parcel','code':'trackparcel'},
{'title':'TRAKPAK','code':'trakpak'},
{'title':'五六快运','code':'wuliuky'},
{'title':'友家速递','code':'youjia'},
{'title':'天天快物流','code':'guoeryue'},
{'title':'皇家物流','code':'pfcexpress'},
{'title':'北京EMS','code':'bjemstckj'},
{'title':'西翼物流','code':'westwing'},
{'title':'亚风速递','code':'yafengsudi'},
{'title':'如家国际快递','code':'homecourier'},
{'title':'极光转运','code':'jiguang'},
{'title':'秦邦快运','code':'qbexpress'},
{'title':'新加坡小包(Singapore Post)','code':'singpost'},
{'title':'汇达物流','code':'hdcexpress'},
{'title':'货运皇','code':'kingfreight'},
{'title':'突尼斯EMS(Rapid-Poste)','code':'tunisia'},
{'title':'优海国际速递','code':'uhi'},
{'title':'BFEX国际速递','code':'bfspeed'},
{'title':'云邮跨境快递','code':'hkems'},
{'title':'聚鼎物流','code':'juding'},
{'title':'科捷物流','code':'kejie'},
{'title':'亚马逊中国订单','code':'amazoncnorder'},
{'title':'MoreLink','code':'morelink56'},
{'title':'英超物流','code':'yingchao'},
{'title':'万家康物流','code':'wjkwl'},
{'title':'远成物流','code':'yuanchengwuliu'},
{'title':'中天万运','code':'zhongtianwanyun'},
{'title':'ABF','code':'abf'},
{'title':'飞快达','code':'feikuaida'},
{'title':'莱索托(Lesotho Post)','code':'lesotho'},
{'title':'美西快递','code':'meixi'},
{'title':'顺捷丰达','code':'shunjiefengda'},
{'title':'比利时(Belgium Post)','code':'belgiumpost'},
{'title':'丹麦(Post Denmark)','code':'postdanmarken'},
{'title':'A2U速递','code':'a2u'},
{'title':'陆本速递 LUBEN EXPRESS','code':'luben'},
{'title':'韵丰物流','code':'yunfeng56'},
{'title':'骏达快递','code':'jdexpressusa'},
{'title':'荷兰速递(Nederland Post)','code':'nederlandpost'},
{'title':'武汉优进汇','code':'yjhgo'},
{'title':'澳通华人物流','code':'cllexpress'},
{'title':'泰国（Thailand Thai Post）','code':'thailand'},
{'title':'宇捷通','code':'yujtong'},
{'title':'美国云达','code':'yundaexus'},
{'title':'急递','code':'jdpplus'},
{'title':'宜送物流','code':'yiex'},
{'title':'BHT','code':'bht'},
{'title':'创一快递','code':'chuangyi'},
{'title':'配思货运','code':'peisihuoyunkuaidi'},
{'title':'威时沛运货运','code':'wtdchina'},
{'title':'洋口岸','code':'ykouan'},
{'title':'成都东骏物流','code':'dongjun'},
{'title':'吉捷国际速递','code':'luckyfastex'},
{'title':'民航快递','code':'minghangkuaidi'},
{'title':'远成快运','code':'ycgky'},
{'title':'黑猫速运','code':'heimao56'},
{'title':'俄罗斯邮政(Russian Post)','code':'pochta'},
{'title':'河北橙配','code':'chengpei'},
{'title':'明大快递','code':'adaexpress'},
{'title':'青岛安捷快递','code':'anjiekuaidi'},
{'title':'全川物流','code':'quanchuan56'},
{'title':'全际通','code':'quanjitong'},
{'title':'永邦国际物流','code':'yongbangwuliu'},
{'title':'元智捷诚','code':'yuanzhijiecheng'},
{'title':'泰捷达国际物流','code':'ztjieda'},
{'title':'华中快递','code':'cpsair'},
{'title':'赛澳递for买卖宝','code':'saiaodimmb'},
{'title':'中运全速','code':'topspeedex'},
{'title':'奔腾物流','code':'benteng'},
{'title':'加拿大邮政','code':'canpostfr'},
{'title':'City-Link','code':'citylink'},
{'title':'三志物流','code':'sanzhi56'},
{'title':'深圳邮政','code':'szyouzheng'},
{'title':'邦送物流','code':'bangsongwuliu'},
{'title':'E通速递','code':'etong'},
{'title':'海红网送','code':'haihongwangsong'},
{'title':'维普恩物流','code':'vps'},
{'title':'中粮鲜到家物流','code':'zlxdjwl'},
{'title':'可可树美中速运','code':'excocotree'},
{'title':'凡宇快递','code':'fanyukuaidi'},
{'title':'安的快递','code':'gda'},
{'title':'上海快通','code':'shanghaikuaitong'},
{'title':'新速航','code':'sunspeedy'},
{'title':'新干线快递','code':'anlexpress'},
{'title':'百通物流','code':'buytong'},
{'title':'CNAIR','code':'cnair'},
{'title':'优莎速运','code':'eusacn'},
{'title':'汇强快递','code':'huiqiangkuaidi'},
{'title':'牙买加（Jamaica Post）','code':'jamaicapost'},
{'title':'6LS EXPRESS','code':'lsexpress'},
{'title':'马来西亚小包（Malaysia Post(Registered)）','code':'malaysiapost'},
{'title':'MyHermes','code':'myhermes'},
{'title':'鑫远东速运','code':'xyd666'},
{'title':'增速跨境 ','code':'zyzoom'},
{'title':'法国大包、EMS-英文(Chronopost France)','code':'chronopostfren'},
{'title':'深圳德创物流','code':'dechuangwuliu'},
{'title':'中外运','code':'esinotrans'},
{'title':'飞豹速递','code':'hkeex'},
{'title':'腾达速递','code':'nntengda'},
{'title':'新西兰中通','code':'nzzto'},
{'title':'顺通快递','code':'stkd'},
{'title':'瑞士(Swiss Post)','code':'swisspost'},
{'title':'纵通速运','code':'ynztsy'},
{'title':'澳世速递','code':'ausexpress'},
{'title':'华欣物流','code':'chinastarlogistics'},
{'title':'法国大包、EMS-法文（Chronopost France）','code':'chronopostfra'},
{'title':'递四方澳洲','code':'disifangau'},
{'title':'EASY EXPRESS','code':'easyexpress'},
{'title':'飞狐快递','code':'feihukuaidi'},
{'title':'日日顺智慧物联','code':'gooday365'},
{'title':'全日通','code':'quanritongkuaidi'},
{'title':'保加利亚（Bulgarian Posts）','code':'bulgarian'},
{'title':'大道物流','code':'dadaoex'},
{'title':'英国(大包,EMS)','code':'england'},
{'title':'广通速递','code':'gtongsudi'},
{'title':'捷邦物流','code':'jieborne'},
{'title':'美国快递','code':'meiguokuaidi'},
{'title':'越丰物流','code':'yuefengwuliu'},
{'title':'三三国际物流','code':'zenzen'},
{'title':'ADP国际快递','code':'adp'},
{'title':'澳州顺风快递','code':'emms'},
{'title':'四方格','code':'fourpxus'},
{'title':'共速达','code':'gongsuda'},
{'title':'快速递','code':'ksudi'},
{'title':'马其顿(Macedonian Post)','code':'macedonia'},
{'title':'民邦速递','code':'minbangsudi'},
{'title':'Purolator','code':'purolator'},
{'title':'世华通物流','code':'szshihuatong56'},
{'title':'准实快运','code':'zsky123'},
{'title':'心怡物流','code':'alog'},
{'title':'新喀里多尼亚[法国](New Caledonia)','code':'caledonia'},
{'title':'易优包裹','code':'eupackage'},
{'title':'嘉诚速达','code':'jcsuda'},
{'title':'韩国邮政韩文','code':'koreapostkr'},
{'title':'一号仓','code':'onehcang'},
{'title':'北极星快运','code':'polarisexpress'},
{'title':'7E速递','code':'qesd'},
{'title':'深圳DPEX','code':'szdpex'},
{'title':'易欧洲国际物流','code':'yiouzhou'},
{'title':'志腾物流','code':'zhitengwuliu'},
{'title':'忠信达','code':'zhongxinda'},
{'title':'AOL澳通速递','code':'aolau'},
{'title':'澳速物流','code':'aosu'},
{'title':'阿塞拜疆EMS(EMS AzerExpressPost)','code':'azerbaijan'},
{'title':'贝业物流','code':'boyol'},
{'title':'邦通国际','code':'comexpress'},
{'title':'广州安能聚创物流','code':'gzanjcwl'},
{'title':'柬埔寨中通','code':'khzto'},
{'title':'明亮物流','code':'mingliangwuliu'},
{'title':'斯洛文尼亚(Slovenia Post)','code':'slovenia'},
{'title':'瑞士邮政','code':'swisspostcn'},
{'title':'泰国中通ZTO','code':'thaizto'},
{'title':'伍圆速递','code':'wuyuansudi'},
{'title':'银捷速递','code':'yinjiesudi'},
{'title':'雅澳物流','code':'yourscm'},
{'title':'远为快递','code':'ywexpress'},
{'title':'中环转运','code':'zhonghuanus'},
{'title':'安达易国际速递','code':'adiexpress'},
{'title':'百世云配','code':'baishiyp'},
{'title':'蜜蜂速递','code':'bee001'},
{'title':'彪记快递','code':'biaojikuaidi'},
{'title':'长宇物流','code':'changyuwuliu'},
{'title':'递四方美国','code':'disifangus'},
{'title':'易邮国际','code':'euguoji'},
{'title':'GE2D跨境物流','code':'ge2d'},
{'title':'开心快递','code':'happylink'},
{'title':'华瀚快递','code':'hhair56'},
{'title':'飞鹰物流','code':'hnfy'},
{'title':'红远物流','code':'hongywl'},
{'title':'恒宇运通','code':'hyytes'},
{'title':'大达物流','code':'idada'},
{'title':'嘉里大荣物流','code':'kerrytj'},
{'title':'尼尔快递','code':'nell'},
{'title':'赛澳递','code':'saiaodi'},
{'title':'SkyNet Malaysia','code':'skynetmalaysia'},
{'title':'南非（South African Post Office）','code':'southafrican'},
{'title':'联运通物流','code':'szuem'},
{'title':'通和天下','code':'tonghetianxia'},
{'title':'天天欧洲物流','code':'ttkeurope'},
{'title':'乌克兰小包、大包(UkrPost)','code':'ukrpost'},
{'title':'渥途国际速运','code':'wotu'},
{'title':'臣邦同城','code':'wto56kj'},
{'title':'玥玛速运','code':'yue777'},
{'title':'卓实快运','code':'zhuoshikuaiyun'},
{'title':'中远快运','code':'zy100'},
{'title':'全球快运','code':'abcglobal'},
{'title':'德方物流','code':'ahdf'},
{'title':'中联速递','code':'auvanda'},
{'title':'城市映急','code':'city56'},
{'title':'EU-EXPRESS','code':'euexpress'},
{'title':'高捷快运','code':'goldjet'},
{'title':'海外环球','code':'haiwaihuanqiu'},
{'title':'华企快运','code':'huaqikuaiyun'},
{'title':'爱拜物流','code':'ibuy8'},
{'title':'logen路坚','code':'ilogen'},
{'title':'晋越快递','code':'jinyuekuaidi'},
{'title':'加拿大龙行速运','code':'longcps'},
{'title':'马来西亚大包、EMS（Malaysia Post(parcel,EMS)）','code':'malaysiaems'},
{'title':'猛犸速递','code':'mmlogi'},
{'title':'浩博物流','code':'njhaobo'},
{'title':'日日顺快线','code':'rrskx'},
{'title':'神骏物流','code':'shenjun'},
{'title':'林道国际快递','code':'shlindao'},
{'title':'新加坡EMS、大包(Singapore Speedpost)','code':'speedpost'},
{'title':'穗佳物流','code':'suijiawuliu'},
{'title':'TNT UK','code':'tntuk'},
{'title':'鑫世锐达','code':'xsrd'},
{'title':'中外运速递','code':'zhongwaiyun'},
{'title':'明辉物流','code':'zsmhwl'},
{'title':'捷记方舟','code':'ajexpress'},
{'title':'河南次晨达','code':'ccd'},
{'title':'CE易欧通国际速递','code':'cloudexpress'},
{'title':'中澳速递','code':'cnausu'},
{'title':'重庆星程快递','code':'cqxingcheng'},
{'title':'东风快递','code':'dfkuaidi'},
{'title':'飞邦快递','code':'fbkd'},
{'title':'恒瑞物流','code':'hengrui56'},
{'title':'佳辰国际速递','code':'jiachenexpress'},
{'title':'隆浪快递','code':'longlangkuaidi'},
{'title':'恒通快递','code':'lqht'},
{'title':'MRW','code':'mrw'},
{'title':'Nova Poshta','code':'novaposhta'},
{'title':'英国邮政大包EMS','code':'parcelforcecn'},
{'title':'全之鑫物流','code':'qzx56'},
{'title':'阳光快递','code':'shiningexpress'},
{'title':'嗖一下同城快递','code':'sofast56'},
{'title':'申通新西兰','code':'stonewzealand'},
{'title':'速风快递','code':'sufengkuaidi'},
{'title':'乌兹别克斯坦(Post of Uzbekistan)','code':'uzbekistan'},
{'title':'越南EMS(VNPost Express)','code':'vnpost'},
{'title':'万博快递','code':'wanboex'},
{'title':'小C海淘','code':'xiaocex'},
{'title':'亚马逊中国','code':'yamaxunwuliu'},
{'title':'一邦速递','code':'yibangwuliu'},
{'title':'YODEL','code':'yodel'},
{'title':'远盾物流','code':'yuandun'},
{'title':'安达信','code':'advancing'},
{'title':'Chronopost Portugal','code':'chronopostport'},
{'title':'中骅物流','code':'chunghwa56'},
{'title':'大韩通运','code':'cjkoreaexpress'},
{'title':'C&C国际速递','code':'cncexp'},
{'title':'泰国中通CTO','code':'ctoexp'},
{'title':'天翔东捷运','code':'djy56'},
{'title':'e直运','code':'edtexpress'},
{'title':'阿联酋(Emirates Post)','code':'emirates'},
{'title':'FOX国际快递','code':'fox'},
{'title':'全速快递','code':'fsexp'},
{'title':'海盟速递','code':'haimengsudi'},
{'title':'河南全速通','code':'hnqst'},
{'title':'华夏货运','code':'huaxiahuoyun'},
{'title':'加佳物流','code':'jiajiawl'},
{'title':'加州猫速递','code':'jiazhoumao'},
{'title':'蓝镖快递','code':'lanbiaokuaidi'},
{'title':'OCA Argentina','code':'ocaargen'},
{'title':'鹏程快递','code':'pengcheng'},
{'title':'土耳其','code':'ptt'},
{'title':'十方通物流','code':'sfift'},
{'title':'SHL畅灵国际物流','code':'shlexp'},
{'title':'中外运速递-中文','code':'sinoex'},
{'title':'红马甲物流','code':'sxhongmajia'},
{'title':'Toll Priority(Toll Online)','code':'tollpriority'},
{'title':'优联吉运','code':'uluckex'},
{'title':'YCG物流','code':'ycgglobal'},
{'title':'振捷国际货运','code':'zjgj56'},
{'title':'全程快递','code':'agopost'},
{'title':'澳捷物流','code':'ajlogistics'},
{'title':'amazon-国际订单','code':'amusorder'},
{'title':'爱尔兰(An Post)','code':'anposten'},
{'title':'宝通快递','code':'baotongkd'},
{'title':'白俄罗斯(Belpochta)','code':'belpost'},
{'title':'城铁速递','code':'cex'},
{'title':'哥伦比亚(4-72 La Red Postal de Colombia)','code':'colombia'},
{'title':'阿根廷(Correo Argentina)','code':'correoargentino'},
{'title':'达速物流','code':'dasu'},
{'title':'达方物流','code':'dfpost'},
{'title':'递达速运','code':'didasuyun'},
{'title':'ECMS Express','code':'ecmsglobal'},
{'title':'Fastway Ireland','code':'fastway'},
{'title':'斐济(Fiji Post)','code':'fiji'},
{'title':'高铁快运','code':'gaotieex'},
{'title':'Gati-KWE','code':'gatikwe'},
{'title':'冠捷物流 ','code':'gjwl'},
{'title':'环国运物流','code':'hgy56'},
{'title':'猴急送','code':'hjs'},
{'title':'海联快递','code':'hltop'},
{'title':'高铁速递','code':'hre'},
{'title':'华通快运','code':'htongexpress'},
{'title':'华达快运','code':'huada'},
{'title':'中国香港环球快运','code':'huanqiuabc'},
{'title':'无限速递','code':'igcaexpress'},
{'title':'劲通快递','code':'jintongkd'},
{'title':'约旦(Jordan Post)','code':'jordan'},
{'title':'考拉国际速递','code':'kaolaexpress'},
{'title':'KCS','code':'kcs'},
{'title':'快达物流','code':'kuaidawuliu'},
{'title':'四川快优达速递','code':'kuaiyouda'},
{'title':'Landmark Global','code':'landmarkglobal'},
{'title':'林道国际快递-英文','code':'ldxpres'},
{'title':'乐天速递','code':'ltexp'},
{'title':'中国澳门(Macau Post)','code':'macao'},
{'title':'毛里求斯(Mauritius Post)','code':'mauritius'},
{'title':'OPEK','code':'opek'},
{'title':'PCA Express','code':'pcaexpress'},
{'title':'葡萄牙（Portugal CTT）','code':'portugalctt'},
{'title':'急顺通','code':'pzhjst'},
{'title':'千里速递','code':'qianli'},
{'title':'Quantium','code':'quantium'},
{'title':'S2C','code':'s2c'},
{'title':'速呈','code':'sczpds'},
{'title':'中外运空运','code':'sinoairinex'},
{'title':'苏丹（Sudapost）','code':'sudapost'},
{'title':'速配欧翼','code':'superoz'},
{'title':'天纵物流','code':'tianzong'},
{'title':'通达兴物流','code':'tongdaxing'},
{'title':'USPSCN','code':'uspscn'},
{'title':'威速递','code':'wexpress'},
{'title':'亿领速运','code':'yilingsuyun'},
{'title':'易通达','code':'yitongda'},
{'title':'壹品速递','code':'ypsd'},
{'title':'德国云快递','code':'yunexpress'},
{'title':'众辉达物流','code':'zhdwl'},
{'title':'中宏物流','code':'zhonghongwl'},
{'title':'创运物流','code':'zjcy56'},
{'title':'阿富汗(Afghan Post)','code':'afghan'},
{'title':'apgecommerce','code':'apgecommerce'},
{'title':'奥地利(Austrian Post)','code':'austria'},
{'title':'AUV国际快递','code':'auvexpress'},
{'title':'帮帮发','code':'bangbangpost'},
{'title':'孟加拉国(EMS)','code':'bangladesh'},
{'title':'飛斯特','code':'bester'},
{'title':'青云物流','code':'bjqywl'},
{'title':'鑫锐达','code':'bjxsrd'},
{'title':'佰乐捷通','code':'bljt56'},
{'title':'BlueDart','code':'bluedart'},
{'title':'标杆物流','code':'bmlchina'},
{'title':'百千诚物流','code':'bqcwl'},
{'title':'柬埔寨(Cambodia Post)','code':'cambodia'},
{'title':'卢森堡航空','code':'cargolux'},
{'title':'捷克（?eská po?ta）','code':'ceskaposta'},
{'title':'塞浦路斯(Cyprus Post)','code':'cypruspost'},
{'title':'德中快递','code':'decnlh'},
{'title':'DHL HK','code':'dhlhk'},
{'title':'E跨通','code':'ecallturn'},
{'title':'龙象国际物流','code':'edragon'},
{'title':'易联通达','code':'el56'},
{'title':'europeanecom','code':'europeanecom'},
{'title':'颿达国际快递-英文','code':'fandaguoji'},
{'title':'颿达国际快递','code':'fardarww'},
{'title':'FedRoad 联邦转运','code':'fedroad'},
{'title':'凤凰快递','code':'fenghuangkuaidi'},
{'title':'FQ狂派速递','code':'freakyquick'},
{'title':'飞云快递系统','code':'fyex'},
{'title':'新鹏快递','code':'gdxp'},
{'title':'环创物流','code':'ghl'},
{'title':'哥士传奇速递','code':'gscq365'},
{'title':'万通快递','code':'gswtkd'},
{'title':'GTT EXPRESS快递','code':'gttexpress'},
{'title':'冠庭国际物流','code':'guanting'},
{'title':'贵州星程快递','code':'gzxingcheng'},
{'title':'海星桥快递','code':'haixingqiao'},
{'title':'航宇快递','code':'hangyu'},
{'title':'好又快物流','code':'haoyoukuai'},
{'title':'Hi淘易快递','code':'hitaoe'},
{'title':'顺时达物流','code':'hnssd56'},
{'title':'宏品物流','code':'hongpinwuliu'},
{'title':'皇家云仓','code':'hotwms'},
{'title':'海淘物流','code':'ht22'},
{'title':'环东物流','code':'huandonglg'},
{'title':'匈牙利（Magyar Posta）','code':'hungary'},
{'title':'兰州伙伴物流','code':'huoban'},
{'title':'艾姆勒','code':'imlb2c'},
{'title':'印度尼西亚EMS(Pos Indonesia-EMS)','code':'indonesia'},
{'title':'UPS i-parcel','code':'iparcel'},
{'title':'Italy SDA','code':'italysad'},
{'title':'澳速通国际速递','code':'jetexpressgroup'},
{'title':'吉祥邮（澳洲）','code':'jixiangyouau'},
{'title':'佳捷翔物流','code':'jjx888'},
{'title':'哈萨克斯坦(Kazpost)','code':'kazpost'},
{'title':'凯信达','code':'kxda'},
{'title':'跨跃国际','code':'kyue'},
{'title':'拉脱维亚(Latvijas Pasts)','code':'latvia'},
{'title':'新易泰','code':'lnet'},
{'title':'鲁通快运','code':'lutong'},
{'title':'迈隆递运','code':'mailongdy'},
{'title':'马尔代夫(Maldives Post)','code':'maldives'},
{'title':'马耳他（Malta Post）','code':'malta'},
{'title':'木春货运','code':'mchy'},
{'title':'美泰物流','code':'meitai'},
{'title':'NLE','code':'nle'},
{'title':'亚欧专线','code':'nlebv'},
{'title':'华赫物流','code':'nmhuahe'},
{'title':'巴基斯坦(Pakistan Post)','code':'pakistan'},
{'title':'菲律宾（Philippine Postal）','code':'phlpost'},
{'title':'Portugal Seur','code':'portugalseur'},
{'title':'ANTS EXPRESS','code':'qdants'},
{'title':'千顺快递','code':'qskdyxgs'},
{'title':'全通快运','code':'quantwl'},
{'title':'人人转运','code':'renrenex'},
{'title':'rpx','code':'rpx'},
{'title':'日日通国际','code':'rrthk'},
{'title':'三盛快递','code':'sanshengco'},
{'title':'首达速运','code':'sdsy888'},
{'title':'塞尔维亚(PE Post of Serbia)','code':'serbia'},
{'title':'苏豪快递','code':'shipsoho'},
{'title':'顺邦国际物流','code':'shunbang'},
{'title':'荷兰Sky Post','code':'skypost'},
{'title':'斯里兰卡(Sri Lanka Post)','code':'slpost'},
{'title':'行必达','code':'speeda'},
{'title':'申必达','code':'speedoex'},
{'title':'首通快运','code':'staky'},
{'title':'星运快递','code':'staryvr'},
{'title':'智德物流','code':'stzd56'},
{'title':'速品快递','code':'supinexpress'},
{'title':'天美快递','code':'taimek'},
{'title':'天联快运','code':'tlky'},
{'title':'乌克兰小包、大包(UkrPoshta)','code':'ukraine'},
{'title':'越中国际物流','code':'vctrans'},
{'title':'越南小包(Vietnam Posts)','code':'vietnam'},
{'title':'豌豆物流','code':'wandougongzhu'},
{'title':'万达美','code':'wdm'},
{'title':'WTD海外通','code':'wtdex'},
{'title':'蓝天物流','code':'xflt56'},
{'title':'新元快递','code':'xingyuankuaidi'},
{'title':'新宁物流','code':'xinning'},
{'title':'西邮寄','code':'xipost'},
{'title':'一辉物流','code':'yatfai'},
{'title':'云达通','code':'ydglobe'},
{'title':'YDH','code':'ydhex'},
{'title':'易航物流','code':'yihangmall'},
{'title':'亿顺航','code':'yishunhang'},
{'title':'运通快运','code':'ytky168'},
{'title':'远航国际快运','code':'yuanhhk'},
{'title':'一运全成物流','code':'yyqc56'},
{'title':'中技物流','code':'zhongjiwuliu'},
{'title':'众派速递','code':'zhpex'},
{'title':'德国雄鹰速递','code':'adlerlogi'},
{'title':'AFL','code':'afl'},
{'title':'卡邦配送','code':'ahkbps'},
{'title':'加拿大民航快递','code':'airgtc'},
{'title':'阿尔巴尼亚(Posta shqipatre)','code':'albania'},
{'title':'amazon-国内订单','code':'amcnorder'},
{'title':'安家同城快运','code':'anjiatongcheng'},
{'title':'美国汉邦快递','code':'aplus100'},
{'title':'Aplus物流','code':'aplusex'},
{'title':'艾瑞斯远','code':'ariesfar'},
{'title':'阿鲁巴[荷兰]（Post Aruba）','code':'aruba'},
{'title':'澳达国际物流','code':'auadexpress'},
{'title':'澳货通','code':'auex'},
{'title':'澳邦国际物流','code':'ausbondexpress'},
{'title':'澳新物流','code':'axexpress'},
{'title':'巴林(Bahrain Post)','code':'bahrain'},
{'title':'报通快递','code':'baoxianda'},
{'title':'巴巴多斯(Barbados Post)','code':'barbados'},
{'title':'BCWELT','code':'bcwelt'},
{'title':'伯利兹(Belize Postal)','code':'belize'},
{'title':'笨鸟国际','code':'benniao'},
{'title':'波黑(JP BH Posta)','code':'bohei'},
{'title':'玻利维亚','code':'bolivia'},
{'title':'BorderGuru','code':'borderguru'},
{'title':'堡昕德速递','code':'bosind'},
{'title':'博茨瓦纳','code':'botspost'},
{'title':'速方(Sufast)','code':'bphchina'},
{'title':'巴西(Brazil Post/Correios)','code':'brazilposten'},
{'title':'文莱(Brunei Postal)','code':'brunei'},
{'title':'到了港','code':'camekong'},
{'title':'Campbell’s Express','code':'campbellsexpress'},
{'title':'能装能送','code':'canhold'},
{'title':'钏博物流','code':'cbo56'},
{'title':'捷祥物流','code':'cdjx56'},
{'title':'鑫宸物流','code':'cdxinchen56'},
{'title':'CEVA Logistic','code':'cevalogistics'},
{'title':'银雁专送','code':'cfss'},
{'title':'昌宇国际','code':'changwooair'},
{'title':'成达国际速递','code':'chengda'},
{'title':'城际快递','code':'chengji'},
{'title':'智利(Correos Chile)','code':'chile'},
{'title':'SQK国际速递','code':'chinasqk'},
{'title':'同舟行物流','code':'chinatzx'},
{'title':'嘉荣物流','code':'chllog'},
{'title':'中国香港骏辉物流','code':'chunfai'},
{'title':'citysprint','code':'citysprint'},
{'title':'长吉物流','code':'cjqy'},
{'title':'CL日中速运','code':'clsp'},
{'title':'中欧物流','code':'cneulogistics'},
{'title':'CNUP 中联邮','code':'cnup'},
{'title':'中国翼','code':'cnws'},
{'title':'莫桑比克（Correios de Moçambique）','code':'correios'},
{'title':'乌拉圭（Correo Uruguayo）','code':'correo'},
{'title':'哥斯达黎加(Correos de Costa Rica)','code':'correos'},
{'title':'环旅快运','code':'crossbox'},
{'title':'新时速物流','code':'csxss'},
{'title':'云南诚中物流','code':'czwlyn'},
{'title':'丹递56','code':'dande56'},
{'title':'DCS','code':'dcs'},
{'title':'Deltec Courier','code':'deltec'},
{'title':'澳行快递','code':'desworks'},
{'title':'DHL-荷兰（DHL Netherlands）','code':'dhlnetherlands'},
{'title':'DHL-波兰（DHL Poland）','code':'dhlpoland'},
{'title':'云南滇驿物流','code':'dianyi'},
{'title':'叮咚澳洲转运','code':'dindon'},
{'title':'叮咚快递','code':'dingdong'},
{'title':'Direct Link','code':'directlink'},
{'title':'东瀚物流','code':'donghanwl'},
{'title':'东红物流','code':'donghong'},
{'title':'DPD Germany','code':'dpdgermany'},
{'title':'DPD Poland','code':'dpdpoland'},
{'title':'DPD UK','code':'dpduk'},
{'title':'DTDC India','code':'dtdcindia'},
{'title':'多道供应链','code':'duodao56'},
{'title':'东方航空物流','code':'ealceair'},
{'title':'EC-Firstclass','code':'ecfirstclass'},
{'title':'东西E全运','code':'ecotransite'},
{'title':'厄瓜多尔(Correos del Ecuador)','code':'ecuador'},
{'title':'易达快运','code':'edaeuexpress'},
{'title':'EFSPOST','code':'efspost'},
{'title':'埃及（Egypt Post）','code':'egypt'},
{'title':'艾菲尔国际速递','code':'eiffel'},
{'title':'希腊包裹（ELTA Hellenic Post）','code':'elta'},
{'title':'希腊EMS（ELTA Courier）','code':'eltahell'},
{'title':'波兰小包(Poczta Polska)','code':'emonitoring'},
{'title':'南非EMS','code':'emssouthafrica'},
{'title':'乌克兰EMS(EMS Ukraine)','code':'emsukraine'},
{'title':'乌克兰EMS-中文(EMS Ukraine)','code':'emsukrainecn'},
{'title':'联众国际','code':'epspost'},
{'title':'贰仟家物流','code':'erqianjia56'},
{'title':'Estafeta','code':'estafeta'},
{'title':'Estes','code':'estes'},
{'title':'易达国际速递','code':'eta100'},
{'title':'ETEEN专线','code':'eteenlog'},
{'title':'埃塞俄比亚(Ethiopian postal)','code':'ethiopia'},
{'title':'中欧国际物流','code':'eucnrail'},
{'title':'德国 EUC POST','code':'eucpost'},
{'title':'败欧洲','code':'europe8'},
{'title':'澳洲新干线快递','code':'expressplus'},
{'title':'易转运','code':'ezhuanyuan'},
{'title':'加拿大联通快运','code':'fastontime'},
{'title':'正途供应链','code':'fastzt'},
{'title':'FedEx-英国件（FedEx UK)','code':'fedexuk'},
{'title':'FedEx-英国件','code':'fedexukcn'},
{'title':'丰羿','code':'fengyee'},
{'title':'芬兰(Itella Posti Oy)','code':'finland'},
{'title':'花瓣转运','code':'flowerkd'},
{'title':'法翔速运','code':'ftlexpress'},
{'title':'Gati-英文','code':'gatien'},
{'title':'全网物流','code':'gdqwwl'},
{'title':'容智快运','code':'gdrz58'},
{'title':'格鲁吉亚(Georgian Pos）','code':'georgianpost'},
{'title':'GHT物流','code':'ghtexpress'},
{'title':'直布罗陀[英国]( Royal Gibraltar Post)','code':'gibraltar'},
{'title':'全球特快','code':'global99'},
{'title':'globaltracktrace','code':'globaltracktrace'},
{'title':'英脉物流','code':'gml'},
{'title':'格陵兰[丹麦]（TELE Greenland A/S）','code':'greenland'},
{'title':'潍鸿','code':'grivertek'},
{'title':'GT国际快运','code':'gtgogo'},
{'title':'国送快运','code':'guosong'},
{'title':'宏观国际快递','code':'gvpexpress'},
{'title':'光线速递','code':'gxwl'},
{'title':'海红for买卖宝','code':'haihongmmb'},
{'title':'海中转运','code':'haizhongzhuanyun'},
{'title':'汉邦国际速递','code':'handboy'},
{'title':'翰丰快递','code':'hanfengjl'},
{'title':'亚美尼亚(Haypost-Armenian Postal)','code':'haypost'},
{'title':'互联快运','code':'hlkytj'},
{'title':'共联配','code':'hlpgyl'},
{'title':'中强物流','code':'hnzqwl'},
{'title':'居家通','code':'homexpress'},
{'title':'红背心','code':'hongbeixin'},
{'title':'宏捷国际物流','code':'hongjie'},
{'title':'环球通达 ','code':'hqtd'},
{'title':'卓烨快递','code':'hrbzykd'},
{'title':'克罗地亚（Hrvatska Posta）','code':'hrvatska'},
{'title':'海硕高铁速递','code':'hsgtsd'},
{'title':'华通务达物流','code':'htwd'},
{'title':'驼峰国际','code':'humpline'},
{'title':'户通物流','code':'hutongwuliu'},
{'title':'鸿远物流','code':'hyeship'},
{'title':'上海昊宏国际货物','code':'hyk'},
{'title':'华航快递','code':'hzpl'},
{'title':'冰岛(Iceland Post)','code':'iceland'},
{'title':'泛太优达','code':'iex'},
{'title':'iExpress','code':'iexpress'},
{'title':'ILYANG','code':'ilyang'},
{'title':'印度(India Post)','code':'india'},
{'title':'多米尼加（INPOSDOM – Instituto Postal Dominicano）','code':'inposdom'},
{'title':'Interlink Express','code':'interlink'},
{'title':'伊朗（Iran Post）','code':'iran'},
{'title':'以色列(Israel Post)','code':'israelpost'},
{'title':'驿扬国际速运','code':'iyoungspeed'},
{'title':'jcex','code':'jcex'},
{'title':'泽西岛','code':'jerseypost'},
{'title':'佳家通货运','code':'jiajiatong56'},
{'title':'锦程物流','code':'jinchengwuliu'},
{'title':'冀速物流','code':'jisu'},
{'title':'九宫物流','code':'jiugong'},
{'title':'久易快递','code':'jiuyicn'},
{'title':'骏绅物流','code':'jsexpress'},
{'title':'聚物物流','code':'juwu'},
{'title':'聚中大','code':'juzhongda'},
{'title':'肯尼亚(POSTA KENYA)','code':'kenya'},
{'title':'启邦国际物流','code':'keypon'},
{'title':'快服务','code':'kfwnet'},
{'title':'跨境直邮通','code':'kjde'},
{'title':'番薯国际货运','code':'koali'},
{'title':'淘韩国际快递','code':'krtao'},
{'title':'快8速运','code':'kuai8'},
{'title':'快淘快递','code':'kuaitao'},
{'title':'吉尔吉斯斯坦(Kyrgyz Post)','code':'kyrgyzpost'},
{'title':'蓝弧快递','code':'lanhukuaidi'},
{'title':'老挝(Lao Express) ','code':'lao'},
{'title':'塞内加尔','code':'laposte'},
{'title':'林安物流','code':'lasy56'},
{'title':'立白宝凯物流','code':'lbbk'},
{'title':'楽道物流','code':'ledaowuliu'},
{'title':'乐递供应链','code':'ledii'},
{'title':'云豹国际货运','code':'leopard'},
{'title':'美联快递','code':'letseml'},
{'title':'lazada','code':'lgs'},
{'title':'联合速递','code':'lhexpressus'},
{'title':'联运快递','code':'lianyun'},
{'title':'黎巴嫩(Liban Post)','code':'libanpost'},
{'title':'Linex','code':'linex'},
{'title':'丽狮物流','code':'lishi'},
{'title':'立陶宛（Lietuvos pa?tas）','code':'lithuania'},
{'title':'小熊物流','code':'littlebearbear'},
{'title':'良藤国际速递','code':'lmfex'},
{'title':'華信物流WTO','code':'logistics'},
{'title':'长风物流','code':'longvast'},
{'title':'联通快递','code':'ltparcel'},
{'title':'论道国际物流','code':'lundao'},
{'title':'卢森堡(Luxembourg Post)','code':'luxembourg'},
{'title':'LWE','code':'lwe'},
{'title':'麦力快递','code':'mailikuaidi'},
{'title':'芒果速递','code':'mangguo'},
{'title':'今枫国际快运','code':'mapleexpress'},
{'title':'澳洲迈速快递','code':'maxeedexpress'},
{'title':'美邦国际快递','code':'meibang'},
{'title':'美达快递','code':'meidaexpress'},
{'title':'墨西哥（Correos de Mexico）','code':'mexico'},
{'title':'Mexico Senda Express','code':'mexicodenda'},
{'title':'银河物流','code':'milkyway'},
{'title':'美龙快递','code':'mjexp'},
{'title':'摩尔多瓦(Posta Moldovei)','code':'moldova'},
{'title':'蒙古国(Mongol Post) ','code':'mongolpost'},
{'title':'黑山(Posta Crne Gore)','code':'montenegro'},
{'title':'摩洛哥 ( Morocco Post )','code':'morocco'},
{'title':'Mexico Multipack','code':'multipack'},
{'title':'中俄速通（淼信）','code':'mxe56'},
{'title':'新亚物流','code':'nalexpress'},
{'title':'纳米比亚(NamPost)','code':'namibia'},
{'title':'红马速递','code':'nedahm'},
{'title':'尼泊尔（Nepal Postal Services）','code':'nepalpost'},
{'title':'尼日利亚(Nigerian Postal)','code':'nigerianpost'},
{'title':'牛仔速运','code':'niuzaiexpress'},
{'title':'诺尔国际物流','code':'nuoer'},
{'title':'偌亚奥国际快递','code':'nuoyaao'},
{'title':'OC-Post','code':'ocpost'},
{'title':'阿曼(Oman Post)','code':'oman'},
{'title':'爱沙尼亚(Eesti Post)','code':'omniva'},
{'title':'昂威物流','code':'onway'},
{'title':'波音速递','code':'overseaex'},
{'title':'巴拉圭(Correo Paraguayo)','code':'paraguay'},
{'title':'诚一物流','code':'parcelchina'},
{'title':'普畅物流','code':'pcwl56'},
{'title':'全球速递','code':'pdstow'},
{'title':'派尔快递','code':'peex'},
{'title':'陪行物流','code':'peixingwuliu'},
{'title':'秘鲁(SERPOST)','code':'peru'},
{'title':'品速心达快递','code':'pinsuxinda'},
{'title':'品信快递','code':'pinxinkuaidi'},
{'title':'先锋国际快递','code':'pioneer'},
{'title':'龙行天下','code':'pmt0704be'},
{'title':'坦桑尼亚（Tanzania Posts Corporation）','code':'posta'},
{'title':'PostElbe','code':'postelbe'},
{'title':'PostNord(Posten AB)','code':'postenab'},
{'title':'挪威（Posten Norge）','code':'postennorge'},
{'title':'巴布亚新几内亚(PNG Post)','code':'postpng'},
{'title':'雪域快递','code':'qhxykd'},
{'title':'启辰国际速递','code':'qichen'},
{'title':'全信通快递','code':'quanxintong'},
{'title':'Red Express','code':'redexpress'},
{'title':'叙利亚(Syrian Post)','code':'republic'},
{'title':'睿和泰速运','code':'rhtexpress'},
{'title':'日昱物流','code':'riyuwuliu'},
{'title':'荣庆物流','code':'rokin'},
{'title':'罗马尼亚（Posta Romanian）','code':'romanian'},
{'title':'卢旺达(Rwanda i-posita)','code':'rwanda'},
{'title':'Safexpress','code':'safexpress'},
{'title':'萨摩亚(Samoa Post)','code':'samoa'},
{'title':'沙特阿拉伯(Saudi Post)','code':'saudipost'},
{'title':'中加国际快递','code':'scic'},
{'title':'速佳达快运','code':'scsujiada'},
{'title':'四川星程快递','code':'scxingcheng'},
{'title':'Selektvracht','code':'selektvracht'},
{'title':'International Seur','code':'seur'},
{'title':'澳丰速递','code':'sfau'},
{'title':'圣飞捷快递','code':'sfjhd'},
{'title':'曹操到','code':'sfpost'},
{'title':'衫达快运','code':'shanda56'},
{'title':'上海无疆for买卖宝','code':'shanghaiwujiangmmb'},
{'title':'尚途国际货运','code':'shangtuguoji'},
{'title':'闪货极速达','code':'shanhuodidi'},
{'title':'捎客物流','code':'shaoke'},
{'title':'杰响物流','code':'shbwch'},
{'title':'商海德物流','code':'shd56'},
{'title':'盛通快递','code':'shengtongscm'},
{'title':'神马快递','code':'shenma'},
{'title':'王牌快递','code':'shipbyace'},
{'title':'世运快递','code':'shiyunkuaidi'},
{'title':'wish邮','code':'shpostwish'},
{'title':'顺士达速运','code':'shunshid'},
{'title':'四海快递','code':'sihaiet'},
{'title':'四海捷运','code':'sihiexpress'},
{'title':'Siodemka','code':'siodemka'},
{'title':'易普递','code':'sixroad'},
{'title':'skynet','code':'skynet'},
{'title':'skynetworldwide','code':'skynetworldwide'},
{'title':'斯洛伐克(Slovenská Posta)','code':'slovak'},
{'title':'星速递','code':'starex'},
{'title':'速豹','code':'subaoex'},
{'title':'速呈宅配','code':'sucheng'},
{'title':'特急便物流','code':'sucmj'},
{'title':'郑州速捷','code':'sujievip'},
{'title':'泰进物流','code':'taijin'},
{'title':'坦桑尼亚(Tanzania Posts)','code':'tanzania'},
{'title':'TCI XPS','code':'tcixps'},
{'title':'TCXB国际物流','code':'tcxbthai'},
{'title':'TD Cargo','code':'tdcargo'},
{'title':'加拿大雷霆快递','code':'thunderexpress'},
{'title':'天翔快递','code':'tianxiang'},
{'title':'株式会社T.M.G','code':'tmg'},
{'title':'TNT Italy','code':'tntitaly'},
{'title':'TNT Post','code':'tntpostcn'},
{'title':'TNY物流','code':'tny'},
{'title':'顶世国际物流','code':'topshey'},
{'title':'海龟国际快递','code':'turtle'},
{'title':'天翼物流','code':'tywl99'},
{'title':'UEX国际物流','code':'uex'},
{'title':'欧洲UEX','code':'uexiex'},
{'title':'乌干达(Posta Uganda)','code':'uganda'},
{'title':'邮鸽速运','code':'ugoexpress'},
{'title':'UPS Freight','code':'upsfreight'},
{'title':'UPS Mail Innovations','code':'upsmailinno'},
{'title':'华夏国际速递','code':'uschuaxia'},
{'title':'UTAO优到','code':'utaoscm'},
{'title':'万庚国际速递','code':'vangenexpress'},
{'title':'瓦努阿图(Vanuatu Post)','code':'vanuatu'},
{'title':'鹰运国际速递','code':'vipexpress'},
{'title':'宁夏万家通','code':'wanjiatong'},
{'title':'文捷航空','code':'wenjiesudi'},
{'title':'香港伟豪国际物流','code':'whgjkd'},
{'title':'万邑通','code':'winit'},
{'title':'凡仕特物流','code':'wlfast'},
{'title':'沃埃家','code':'wowvip'},
{'title':'万运国际快递','code':'wygj168'},
{'title':'微转运','code':'wzhaunyun'},
{'title':'国晶物流','code':'xdshipping'},
{'title':'鑫宏福物流','code':'xhf56'},
{'title':'西安城联速递','code':'xianchengliansudi'},
{'title':'湘达物流','code':'xiangdawuliu'},
{'title':'祥龙运通物流','code':'xianglongyuntong'},
{'title':'翔腾物流','code':'xiangteng'},
{'title':'西安喜来快递','code':'xilaikd'},
{'title':'鑫通宝物流','code':'xtb'},
{'title':'西游寄速递','code':'xyjexpress'},
{'title':'易达丰国际速递','code':'ydfexpress'},
{'title':'也门(Yemen Post)','code':'yemen'},
{'title':'驿递汇速递','code':'yidihui'},
{'title':'艺凡快递','code':'yifankd'},
{'title':'一柒国际物流','code':'yiqiguojiwuliu'},
{'title':'宜送','code':'yisong'},
{'title':'易邮速运','code':'yiyou'},
{'title':'邮来速递','code':'youlai'},
{'title':'粤中国际货运代理（上海）有限公司','code':'yuezhongsh'},
{'title':'西安运逸快递','code':'yyexp'},
{'title':'珠峰速运','code':'zf365'},
{'title':'众川国际','code':'zhongchuan'},
{'title':'转瞬达集运','code':'zsda56'},
{'title':'中途速递','code':'ztcce'},
{'title':'ZTE中兴物流','code':'zteexpress'}
]";
    }
}